version: '3.8'

services:
  app:
    build: .
    container_name: backend
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
    environment:
      - DB_PATH=/app/data/storage.db
      - PORT=8080
    restart: unless-stopped